### ISSUE TITLE
Error when loading page served by ember server

### ISSUE THREAD

**Issue by Frando** [archSeer/colibri#2]
After npm install and bower install, I ran ember server. When opening http://localhost:4200 in a browser, I get the following in both the browser and in the ember-cli stdout (actual path replaced with DOCROOT).

ENOENT: no such file or directory, stat 'DOCROOT/colibri/tmp/concat_with_maps-input_base_path-0bkikJV1.tmp/0/bower_components/audio5/audio5.min.js'
Error: ENOENT: no such file or directory, stat 'DOCROOT/colibri/tmp/concat_with_maps-input_base_path-0bkikJV1.tmp/0/bower_components/audio5/audio5.min.js'
    at Error (native)
    at Object.fs.statSync (fs.js:893:18)
    at ConcatWithMaps.keyForFile (DOCROOT/colibri/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (DOCROOT/colibri/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at DOCROOT/colibri/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (DOCROOT/colibri/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (DOCROOT/colibri/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (DOCROOT/colibri/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (DOCROOT/colibri/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by archSeer** [comment]
Oops, sorry for that! https://github.com/archSeer/colibri/commit/4342e6d0d1604286f25e4d5e23ee0c008ab33edf should fix that, you'll need to pull then do `bower install` once more.

**Comment by archSeer** [comment]
I'll close this for now, assuming that's fixed with https://github.com/archSeer/colibri/commit/4342e6d0d1604286f25e4d5e23ee0c008ab33edf.
